### ISSUE TITLE
WrapRepeaterView spacing is ignored

### ISSUE THREAD

**Issue by apostolsergii** [DottorPagliaccius/Xamarin-Custom-Controls#10]
Hi, I was playing around WrapRepeaterView and realized that Spacing property is not in use. 
Could you please use value of Spacing property for ColumnSpacing and RowSpacing. Or just remove Spacing property as it is misleading

**Comment by DottorPagliaccius** [comment]
You're right, Spacing property is ignored. I don't know why I've add it in the first place, it makes no sense since there are the ColumnSpacing and RowSpacing properties inherited from Grid. I'll remove it in the next version, thank you.
