### ISSUE TITLE
RepeaterView: is it possible to use it to simulate a "multicolumn" ListView?

### ISSUE THREAD

**Issue by Goldstrike** [DottorPagliaccius/Xamarin-Custom-Controls#12]
Hello,
I'm looking for the better way to implement a control that looks like a ListView on 2 columns, where each column must have different height.
The excpected result is something like [this](https://preview.ibb.co/kGYFjG/Flow_Layout.png).

The items of these 2 columns come from the same DataSource, and this DataSource can have between 1 and a dozen of items. The items must be splitted automatically (pair/impair), and when the user click on the button related to the item, this must open the item's detail page.

I think that a Repeater item could be a great choice, but I don't see how to implement it for a "multicolumn" use.

**_Is it possible? Or do you have another suggestion?_**

**Comment by DottorPagliaccius** [comment]
Uhm it's not an easy thing to do with a single control; however, I think you can simulate the same behaviour putting two (or more) distinct RepeaterView in a Grid with two (or more) columns, than assign to each of them a DataSource with odd/even elements separated.

Something like:

var leftColumnDataSource = DataSource.Where((c, i) => i % 2 != 0);
var rightColumnDataSource = DataSource.Where((c, i) => i % 2 == 0);

Hope it helps ;)

Bye
