### ISSUE TITLE
Needs to target .Net Standard 1.0 

### ISSUE THREAD

**Issue by wtheronjones** [DottorPagliaccius/Xamarin-Custom-Controls#13]
Hi, I can't target use this in a project because the Portable library type is using profile based portability, instead of the .Net Standard 1.0.   .Net Standard is in use by the latest version of Xamarin Forms, which I am also using.
Perhaps an update for the nuspec is in order?

Thanks!

**Comment by DottorPagliaccius** [comment]
Hi, I thought I have retargeted all libraries. Which package are you referring to?

Thanks
