### ISSUE TITLE
UWP Support for Repeater Control

### ISSUE THREAD

**Issue by hamid-shaikh** [DottorPagliaccius/Xamarin-Custom-Controls#14]
I am being using Repeater Control for my XF project and successfully released support for Android and iOS, Now we are thinking of supporting UWP project also and wanted to leaverage the shared code.

My shared XAML code support all the controls expect Repeater Control.

Requesting to please add a **support** for UWP project also.

**Comment by DottorPagliaccius** [comment]
Hi @hamid-shaikh, I'm glad you're finding my control useful. I usually don't work in UWP and sadly I have no time to support it. These controls are pure XF code with no custom renderers, so they SHOULD work in UWP, but I never tested them. If you want you can add the support yourself, I'll evealuate a pull request.

**Comment by hamid-shaikh** [comment]
Hi @DottorPagliaccius thanks for your response on this. 
As these controls are totally created with out platform specific renderer logic then it should definitely work on UWP platform, will give it a try and update with my findings. 
Note:- Currently don't have window 10 system to test it but will surely test it once windows 10 desktop system is available.
Thanks for creating and sharing valuable controls. 👍

**Comment by DottorPagliaccius** [comment]
Thank you ;) Let me know if you find something about UWP support.
