### ISSUE TITLE
AccordionItemClickEventArgs should derive from System.EventArgs

### ISSUE THREAD

**Issue by tbaggett** [DottorPagliaccius/Xamarin-Custom-Controls#15]
I am using both your accordion view component and the Prism MVVM framework in my project. I am attempting to use Prism's EventToCommandBehavior to map the AccordionItemView's OnClick event to a command in my view model. I am unable to do that due to the AccordionItemClickEventArgs class not extending the System.EventArgs class.

**Comment by DottorPagliaccius** [comment]
AccordionItemClickEventArgs was not extending EventArgs? OMG, where I was looking at. Now (next version) it does, thank you ;)
