### ISSUE TITLE
AccordionRepeaterView Exception messaging incorrect

### ISSUE THREAD

**Issue by tbaggett** [DottorPagliaccius/Xamarin-Custom-Controls#16]
The messaging when an InvalidViewException is thrown in the AccordionRepeaterView class is misleading. It states that the templated control must be a View or ViewCell class instance. However, the check is actually for the view being derived from AccordionItemView.

Excerpt from AccordionRepeaterView.cs:

```
private AccordionItemView GetItemView(object item)
        {
            var content = AccordionItemTemplate.CreateContent();
            if (!(content is AccordionItemView view))
            {
                throw new InvalidViewException($"Templated control must be a View or a ViewCell ({nameof(AccordionItemTemplate)})");
            }

            view.BindingContext = item;

            return view;
        }

```

**Comment by DottorPagliaccius** [comment]
Yes sir, the message is indeed misleading, I will change in the next version, thank you ;)
