### ISSUE TITLE
AccordionView worked in android emulator, dont worked in Orion 4.2.2

### ISSUE THREAD

**Issue by Tical-** [DottorPagliaccius/Xamarin-Custom-Controls#18]

**Comment by Tical-** [comment]
Dont worked in ScrollView, i removed ScrollView and accordion started to work.

**Comment by DottorPagliaccius** [comment]
Forgive my ignorance, what's Orion? It should work inside a Scrollview, can you provide me some xaml so I can chek it?

**Comment by Tical-** [comment]
Sorry for my eng. Orion is old operation system of android.

**Comment by Tical-** [comment]
my company forces everyone to test on such an operating system

**Comment by DottorPagliaccius** [comment]
Sorry but I cant' support a SO if I can't test on it. If you find a fix, do a pull request and I will consider it.
