### ISSUE TITLE
accordion:AccordionItemView not found

### ISSUE THREAD

**Issue by JoshuaNovak919** [DottorPagliaccius/Xamarin-Custom-Controls#2]
I tried making a sample project using the `AccordionView` plugin and the code you used in the CustomControlsSamples project, but I get the following error:

```
Type accordion:AccordionItemView not found in xmlns clr-namespace:Xamarin.CustomControls;assembly=Xamarin.CustomControls.AccordionView
```

Is there something else that is needed to get it to work properly?

**Comment by DottorPagliaccius** [comment]
Uhm I don't know, try posting your code. Are you able to build the sample project without that error?
