### ISSUE TITLE
AccordionItemView RotateImages property is not bindable

### ISSUE THREAD

**Issue by stephanosio** [DottorPagliaccius/Xamarin-Custom-Controls#28]
In AccordionItemView, RotateImages property is not bindable.

It would be nice to have the property bindable so that it can be used in styles.
```
<Style x:Key="AccordionItem" TargetType="accordion:AccordionItemView">
    ...
    <Setter Property="RotateImages" Value="True" />
    ...
</Style>
```

**Comment by DottorPagliaccius** [comment]
Hi @stephanosio, I'll do it as soon as I can.

**Comment by DottorPagliaccius** [comment]
Version 1.1.6 is on its way :sunglasses:
