### ISSUE TITLE
Can not get the sample programs to compile and run.

### ISSUE THREAD

**Issue by WillAutioItrax** [DottorPagliaccius/Xamarin-Custom-Controls#29]
Hi. 
I am trying to run the sample program CustomControlsSample and am getting 34 errors in CustomControlsSamples.csproj when I simply open the solution that are variations on:
`Error	NU1106	Unable to satisfy conflicting requests for 'System.Diagnostics.Tools': `
`System.Diagnostics.Tools (>= 4.3.0) (via package/NETStandard.Library 1.6.1), `
`System.Diagnostics.Tools (>= 4.3.0) (via package/NETStandard.Library 1.6.1), `
`System.Diagnostics.Tools (>= 4.3.0) (via package/NETStandard.Library 1.6.1) `
`Framework: (.NETPortable,Version=v4.5,Profile=Profile111)	`
`CustomControlsSamples	...`

When I try to run the Droid version I get 83 errors - the original ones plus a number that are variations of:
`"CS0234	The type or namespace name 'Forms' does not exist in the namespace 'Xamarin' (are you missing an assembly reference?)"`
(There are different error messages as well, but I expect that if I get past some of these the rest will also go away.)

In the code I get red squiggly lines under : ContentPage with the message:
`"The type or namespace 'Contentpage' could not be found (are you missing a using directive or an assembly reference?)"`

And for InitializeComponent() I get 
`"The name InitializeComponent  does not exist in the current context.`

I expect this works fine for most people. Any insight on how to make it work for me is appreciated.
I'm wondering if I have the wrong version of something, and if so how I would find it?
Thanks!

**Comment by DottorPagliaccius** [comment]
Hi @WillAutioItrax, I've pushed the latest edits, It should be working now. Or at least I hope so :'). Try again and please let me know. Are you working on Mac or Windows?

**Comment by WillAutioItrax** [comment]
Hi @DottorPagliaccius , I am using VS2017 version 15.8.5 on Win 10 desktop. 
I downloaded a new copy of the code with mixed results.
I did not get the "34 errors" mentioned earlier for just opening the project. Yay! 
After building each of the Xamarin.CustomControls.* projects, I tried to run CustomControlSamples.Droid on an android tablet. I got the following errors:
1)
`Severity	Code	Description	Project	File	Line	Suppression State
Error		Error occurred while restoring NuGet packages: An item with the same key has already been added.				

2)
Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1004	Assets file 'C:\Users\will.autio\Documents\...\src\CustomControlsSamples\obj\project.assets.json' not found. 
**Run a NuGet package restore** to generate this file.	
CustomControlsSamples	C:\Program Files\dotnet\sdk\2.1.402\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	198	

3)
Severity	Code	Description	Project	File	Line	Suppression State
Error		The "ResolveLibraryProjectImports" task failed unexpectedly.
System.IO.FileNotFoundException: Could not load assembly 'CustomControlsSamples, Version=0.0.0.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
File name: 'CustomControlsSamples.dll'
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(String fullName)
   at Xamarin.Android.Tasks.ResolveLibraryProjectImports.Extract(DirectoryAssemblyResolver res, ICollection`1 jars, ICollection`1 resolvedResourceDirectories, ICollection`1 resolvedAssetDirectories, ICollection`1 resolvedEnvironments)
   at Xamarin.Android.Tasks.ResolveLibraryProjectImports.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	CustomControlsSamples.Droid			

4)
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0006	Metadata file 'C:\Users\will.autio\Documents\...\src\CustomControlsSamples\bin\Debug\netstandard2.0\CustomControlsSamples.dll' could not be found	CustomControlsSamples.iOS	C:\Users\will.autio\Documents\...\src\iOS\CSC	1	Active

`
Error 1) is new. The first time, I got the other 3 errors. In 2) I read "Run a NuGet package restore" so I tried that and when I ran it again, I got the errors you see before you now.

I think 3) and 4) are because CustomControlsSamples did not compile successfully. That leaves me with 1) and 2). Do you have any insight as to what is missing and how to fix it?
Thanks!
Will

**Comment by WillAutioItrax** [comment]
What?? Somehow I clicked something that closed the issue. Sorry. 
Oh - there are two buttons "Close and Comment" and "Comment". I hit the wrong one.

**Comment by cjkarande** [comment]
hi, any update on this issue. Even i am facing the same issue :(

**Comment by DottorPagliaccius** [comment]
@cjkarande You are on Windows too? Because on my Mac everything's fine, I tried on Windows and I'm having the same problems (more or less). So strange, it should work on either OS. I will do some checks and I'll let you know.

**Comment by cjkarande** [comment]
@DottorPagliaccius  Yes I am on Windows 10. Thanks in advance for your support.

**Comment by DottorPagliaccius** [comment]
@WillAutioItrax @cjkarande try now ;)

**Comment by WillAutioItrax** [comment]
@DottorPagliaccius Awesome!! Works like a charm. Thanks for looking into this for us.

**Comment by DottorPagliaccius** [comment]
Glad to hear that ;)
