### ISSUE TITLE
AccordionView inside a ListView works in Android and UWP but not in iOS

### ISSUE THREAD

**Issue by WillAutioItrax** [DottorPagliaccius/Xamarin-Custom-Controls#30]
Your AccordionView works well for us. In one place I have a number of different types of objects that I need to display inside of a StackLayout. In code, foreach object, I create an AccordionView and an AccordionItem. Then I create and fill a StackLayout appropriate for whatever object needs to be displayed and add it to the accordionItem. This works for iOS, Droid and UWP.

With that win, I turned my attention to a place in out app where we have a ListView and each cell has a lot of data to display. So we thought an AccordionView would be just the thing to display a summary of each record and then expand to show the details. To accomplish this, I put the AccordionView and AccordionItemView inside the ViewCell of the ListView and the stuff to be displayed inside the AccordionItemView. This works fine for Droid and UWP but for iOS it only displays the Text from the AccordionItemView but when it gets tapped it only changes color. It does not reveal what is hidden.

Here is my XAML for the ListView approach:
`        <ListView x:Name="MyLV"  SeparatorVisibility="Default" ItemsSource="{Binding Contacts}"                  
                    HasUnevenRows="True" 
                    Margin="2"
                    BackgroundColor="Black"
                    CachingStrategy="RecycleElement">

            <ListView.ItemTemplate>
                <DataTemplate>
                    <ViewCell >

                        <customcontrols:AccordionView KeepOnlyOneItemOpen="false" Spacing="0">
                            <customcontrols:AccordionView.Children>
                                <customcontrols:AccordionItemView Text="{Binding Name}" ActiveTextColor="Black" TextColor="White"
                                                                  ButtonBackgroundColor="DodgerBlue" ButtonActiveBackgroundColor="DodgerBlue" 
                                                                  TextPosition="Left">

                                    <customcontrols:AccordionItemView.ItemContent>
                                        <Label Text="{Binding Company}" TextColor="White"/>
                                    </customcontrols:AccordionItemView.ItemContent>
                                    
                                </customcontrols:AccordionItemView>
                            </customcontrols:AccordionView.Children>
                        </customcontrols:AccordionView>

                    </ViewCell>
                </DataTemplate>
            </ListView.ItemTemplate>
        </ListView>`

When I ran the XamarinCustomControls I saw AccordionRepeaterViewpage and had a look at how that was done. I tried replicating it unsuccessfully.  At the line:
`BindingContext = _viewModel;`
I get the following exception:
`Xamarin.CustomControls.AccordionView.InvalidViewException: 
'Templated control must be an AccordionItemView (AccordionItemTemplate)'`

Please refer to the following repro:
https://bitbucket.org/WillAutio/accordion/src/master/
In AccordionIssue.MainPage.xaml are two sets of code for displaying the list. One using ListView and one with AccordionRepeaterView. Comment out the one you do not want to run and see what happens.
 
Thanks so much for looking at this. I sure appreciate it.
Regards,
Will

**Comment by DottorPagliaccius** [comment]
Hi @WillAutioItrax. Uhm I don't get it, why are you tryng to use it inside a listview? Since parent AccordionView has no source, is useless, just use the AccordionItem:

```
<ListView x:Name="MyLV"  SeparatorVisibility="Default" ItemsSource="{Binding Contacts}"
                   
                    HasUnevenRows="True" 
                    Margin="2"
                    BackgroundColor="Black"
                    CachingStrategy="RecycleElement">

            <ListView.ItemTemplate>
                <DataTemplate>
                    <ViewCell >
                                <customcontrols:AccordionItemView Text="{Binding Name}" ActiveTextColor="Black" TextColor="White" ButtonBackgroundColor="DodgerBlue" ButtonActiveBackgroundColor="DodgerBlue"  TextPosition="Left">

                                    <customcontrols:AccordionItemView.ItemContent>
                                        <Label Text="{Binding Company}" TextColor="White"/>
                                    </customcontrols:AccordionItemView.ItemContent>
                                    
                                </customcontrols:AccordionItemView>
                   

                    </ViewCell>
                </DataTemplate>
            </ListView.ItemTemplate>
        </ListView>
```

There's no sense for using ListView, because Accordion is itself a "repeater"; the only reason for using it is to resolve performance related issue: the control is not designed to have more than 10/20 children, because it has no Caching strategy so the performance may degrade, especially on Android.

So, your problem: the shitty listview does not autoresize its row, so we have to tell it to. Try this in the "click" event:

```
void Handle_OnClick(object sender, AccordionItemClickEventArgs e)
        {
            var viewCell = ((AccordionItemView)sender).Parent as ViewCell;

            viewCell?.ForceUpdateSize();
        }
```

**Comment by WillAutioItrax** [comment]
Hi @DottorPagliaccius Thanks for your quick response. I tried your suggestion for Handle_OnClick with the ListView. There was no change. The Accordion opened in Android and UWP but not in iOS - as before. I wonder what it is about iOS (or the ListView) that stops it from working like the other two.

However, I took a closer look at your implementation of the AccordionRepeaterView and noticed a bug in my code. Upon commenting out the unnecessary AccordionView, it worked in all three platforms!

~~~~
            <accordion:AccordionRepeaterView KeepOnlyOneItemOpen="False" ItemsSource="{Binding Contacts}">
                <accordion:AccordionRepeaterView.AccordionItemTemplate>
                    <DataTemplate>

                    <!-- <accordion:AccordionView KeepOnlyOneItemOpen="false" Spacing="0"> -->
                        <!--<accordion:AccordionView.Children>-->
                            <accordion:AccordionItemView Text="{Binding Name}" ActiveTextColor="Black" TextColor="White"
                                                ButtonBackgroundColor="DodgerBlue" ButtonActiveBackgroundColor="DodgerBlue" 
                                                TextPosition="Left">

                                <accordion:AccordionItemView.ItemContent>
                                    <Label Text="{Binding Company}" TextColor="White"/>
                                </accordion:AccordionItemView.ItemContent>
        
                            </accordion:AccordionItemView>
                        <!--</accordion:AccordionView.Children>-->
                    <!--</accordion:AccordionView>-->
        
                </DataTemplate>
            </accordion:AccordionRepeaterView.AccordionItemTemplate>
        </accordion:AccordionRepeaterView>`
~~~~
Thanks so much for your help and for publishing this control.
Regards.
Will
PS guess I can Close this for real now ;- )
