### ISSUE TITLE
Nested RepeaterView with efcore sqlite db

### ISSUE THREAD

**Issue by maryjoyquijano** [DottorPagliaccius/Xamarin-Custom-Controls#32]
Hi @DottorPagliaccius,

The nested repeater totally works fine when I use dummy data that is not from database
but when I use database to get the list of feeds the nested repeater is not working on inner repeater (which is "Items" in my example). The parent repeater (which is "Feeds") works fine and showing data on my app.

This is my model

```
public class Feed
{
	public string FeedId { get; set; }
	public string Text { get; set; }
	public ICollection<Item> Items { get; set; }
}

public class Item
{
	public string ItemId { get; set; }
	public string ItemText { get; set; }
	public Feed Feeds { get; set; }
}
```

This is how I do to fetch the list of Feeds in db

```
var feeds = dbcontext.Feeds.Include(i=>i.Items).ToList();

foreach(var feed in feeds)
{
     Feeds.Add(feed);  //bind in ItemsSource="{Binding Feeds}"
}
```
 
Btw, on debug mode I've checked that "Feeds" and its child property "Items" has all the data I needed. 

```
<repeater:RepeaterView x:Name="MainRepeater" ItemsSource="{Binding Feeds}">
	<repeater:RepeaterView.ItemTemplate>
		<DataTemplate>
			<ViewCell>
				<StackLayout Spacing="10">
					<Label Text="{Binding Text}" FontSize="16"  />  
					
					<repeater:RepeaterView x:Name="MainRepeater2" ItemsSource="{Binding Items}">
						<repeater:RepeaterView.ItemTemplate>
							<DataTemplate>
								<ViewCell>
									<StackLayout>
										<Label Text="{Binding ItemText}" TextColor="Black" />  
									</StackLayout>
								</ViewCell>
							</DataTemplate>
						</repeater:RepeaterView.ItemTemplate>
					</repeater:RepeaterView>
				</StackLayout>
			</ViewCell>
		</DataTemplate>
	</repeater:RepeaterView.ItemTemplate>
</repeater:RepeaterView>
```

hope you can help me on this :) thanks.

**Comment by DottorPagliaccius** [comment]
Uhm... if the control works with dummy data, I think the problem is... the data ;) I don't know efcore, but i suspect the problem is the lazy initialization of the child collection (that's why you're seeing it in debug mode, it evaluates itself when you observe it); since is not an observable one, once filled with data it doesn't refresh the control.

Try to make the "Items" Collection a ObservableCollection. Let me know.

**Comment by maryjoyquijano** [comment]
it is now working fine! I just  change Items as ObservableCollection.
Thank you so much for the help and sharing your expertise @DottorPagliaccius  :)

keep on creating amazing control grazie :)

**Comment by DottorPagliaccius** [comment]
ahah "grazie" to you ;)
