### ISSUE TITLE
AutoCompleteView Exception : You must specify SearchMember property

### ISSUE THREAD

**Issue by aditya41295** [DottorPagliaccius/Xamarin-Custom-Controls#34]
Can you tell me what exactly is the SearchMember property and how to specify it in the xaml, I am having a hard time understanding the code. Also, I couldn't find any samples for the autocomplete view, so I am getting difficulties using it.

**Comment by DottorPagliaccius** [comment]
Hi @aditya41295, SearchMember is the name of the field used to perform the search; however, I'm not supporting this control anymore, I advise you to not use it (this is the reason there are no more samples).

You can see the old sample here: https://github.com/DottorPagliaccius/Xamarin-Custom-Controls/commit/3851fc11e2036854c1bacb6233233ceb8359c2d1

bye ;)
