### ISSUE TITLE
KeepOnlyOneItemOpen doesn't work with IsOpen

### ISSUE THREAD

**Issue by mrdnote** [DottorPagliaccius/Xamarin-Custom-Controls#35]
If KeepOnlyOneItemOpen is set, IsOpen doesn't work on the item views. All the items keep closed.

    <accordion:AccordionView KeepOnlyOneItemOpen="False">
        <accordion:AccordionView.Children>
    
            <accordion:AccordionItemView Text="About" IsOpen="True">
                <accordion:AccordionItemView.ItemContent>
    
                    <StackLayout Grid.Row="1" Spacing="0" Padding="15,0">
                        <Label Text="Description" FontAttributes="Bold"></Label>
                        <Label Text="{Binding Description}" FontSize="Small"/>
                    </StackLayout>
    
                </accordion:AccordionItemView.ItemContent>
            </accordion:AccordionItemView>
    
            <accordion:AccordionItemView Text="Promotions" IsOpen="False">
                <accordion:AccordionItemView.ItemContent>
                // ... snip ...

**Comment by DottorPagliaccius** [comment]
Uhm I've used your code and it seems to work as expected, can you send me a sample project?
