### ISSUE TITLE
Xamarin.CustomControls.RepeaterView stopped working with Visual Studio and Xamarin update

### ISSUE THREAD

**Issue by gilles-leblanc** [DottorPagliaccius/Xamarin-Custom-Controls#37]
Hi, 

I have a project that is using the Xamarin.CustomControls.RepeaterView NuGet package. 
I've just updated Visual Studio for Mac and the Xamarin packages for Visual Studio for Mac and my project doesn't compile anymore.

I'm getting an error message saying that: `The type or namespace 'CustomControls' does not exist in the namespace 'Xamarin'.`

I've forked the repository and tried to build it on my Mac. There was an error message about the `armabi` not being supported anymore in the 

Removing this abi allows everything to compile correctly with my updated Visual Studio and Xamarin packages.

One thing I've noticed is that the NuGet package has last been updated in 2017 while there are commits to this repository in 2018.

Could deploying a newer version based on the current code in GitHub fix this issue ?

**Comment by DottorPagliaccius** [comment]
Hi @gilles-leblanc, I don't give support for repeaterview  anymore, there is no reason to use it now that there are valid alternatives (BindableLayout, CollectionView).

**Comment by gilles-leblanc** [comment]
Ok thanks.
I tried to build the package manually and it didn't fix the issue. 
I'll look into the alternatives you mentioned.
