### ISSUE TITLE
Add IsOpened property to AccordionItemView 

### ISSUE THREAD

**Issue by apostolsergii** [DottorPagliaccius/Xamarin-Custom-Controls#4]
It would be nice to have bindable property IsOpened. So it would be possible to programmatically (special with MVVM approach)  control which section is opened

**Comment by DottorPagliaccius** [comment]
Uhm actually the control isn't bindable, its contents are static. However, there is a property called IsOpen, but for now is read-only. If I add the setter you should be able to set it programmatically, but not with binding.

**Comment by apostolsergii** [comment]
It would be nice to have a public setter on IsOpen. Thank you in advance

**Comment by DottorPagliaccius** [comment]
Done ;)
