### ISSUE TITLE
AutocompleteView has no Text property

### ISSUE THREAD

**Issue by softourS** [DottorPagliaccius/Xamarin-Custom-Controls#40]
I believe the title is self explanatory. We are using a couple of AutoCompleteView in order for users to introduce an address (partially) and, when clicking a button, getting a list of addresses which may be the ones they're looking for.

But, we have no clue from where to retrieve the inputed text, since unlike Entries in Forms, AutoCompleteView has no Text property from which we should get the text, and using this sample to get a list of possible addresses.

Please, we need your help with this.

Regards

**Comment by DottorPagliaccius** [comment]
Hi @softourS, 
unfortunately this control is obsolete and I do not give support, I think you shouldn't use it.

However, I can't understand the issue: why should you care for input string? SelectedItem property should be sufficient.

**Comment by softourS** [comment]
Yeah, you're right. We just installed something else.

See ya!

**Comment by DottorPagliaccius** [comment]
;)
