### ISSUE TITLE
StateButton is required for AccordionView

### ISSUE THREAD

**Issue by OpticNectar** [DottorPagliaccius/Xamarin-Custom-Controls#5]
The `AccordionView` requires `StateButton`. If you try to just add `AccordionView` it will crash. `StateButton` should be added as a dependency.

**Comment by DottorPagliaccius** [comment]
Strange, it should be:
![schermata 2017-08-21 alle 11 41 24](https://user-images.githubusercontent.com/7924114/29514905-8d6c56ee-866a-11e7-97cc-499329189033.png)
What I'm missing?

**Comment by OpticNectar** [comment]
Hmm, i'm not sure why it didn't install it's dependencies then.

**Comment by DottorPagliaccius** [comment]
I tried to install the new version of AccordionView and it correctly adds the StateButton too, i'm closing.
