### ISSUE TITLE
Styles don't work for accordion:AccordionItemView

### ISSUE THREAD

**Issue by OpticNectar** [DottorPagliaccius/Xamarin-Custom-Controls#7]
I'm trying to use implicit styles on `accordion:AccordionItemView`, but it crashes my app when I do for some reason. It works for `accordion:AccordionView` though. Here is the code in my `App.xaml` file.

```
<Style TargetType="accordion:AccordionItemView">
    <Setter Property="BorderColor" Value="#ff0000" />
    <Setter Property="Border" Value="0, 0, 0, 1" />
    <Setter Property="TextPosition" Value="Left" />
</Style>
```
**Note:** Sorry for all the issues. This component rocks though! Keep up the good work!

**Comment by DottorPagliaccius** [comment]
Fixed in the next release.

Thank you very much for your help ;)

**Comment by OpticNectar** [comment]
@DottorPagliaccius Just so you know, even in version 1.0.5 styles don't work properly for `AccordionItemView`.

**Comment by DottorPagliaccius** [comment]
It should work know, thank you.
